---
- name: Set apt settings tweaks
  copy:
    src: "apt/{{ item }}"
    dest: /etc/apt/apt.conf.d
    owner: root
    group: root
    mode: 0644
  loop:
    - 10periodic
    - 20auto-upgrades
    - 50unattended-upgrades
    - 99no-recommends
    - 99disable-translations

- name: Update apt caches
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install default packages
  apt:
    pkg: "{{ apt_pkgs_to_install }}"
    state: present

- name: Stop and disable unnecessary daemons
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop: "{{ services_2_disable }}"
  ignore_errors: true

- name: Enable HTTPS transport for apt
  apt:
    pkg: apt-transport-https
    state: present

- name: Symlink bat
  file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    owner: root
    group: root
    state: link

- name: Uninstall Packages
  apt:
    pkg: "{{ apt_pkgs_to_remove }}"
    state: absent
    purge: true
