---
- name: Configure apt + OS packages
  import_tasks: apt.yml

- name: Configure timezone
  import_tasks: timezone.yml

- name: Configure locale
  import_tasks: locale.yml

- name: Copy default config files
  import_tasks: files.yml

- name: Configure rsyslog
  import_tasks: rsyslog.yml

- name: Configure logrotate
  import_tasks: logrotate.yml

- name: Configure ssh
  import_tasks: ssh.yml

- name: Configure sysctl
  import_tasks: sysctl.yml

- name: Configure PAM
  import_tasks: pam.yml
  tags: [common, common_pam]

- name: Configure cron
  import_tasks: cron.yml

- name: Install chrony
  import_tasks: chrony.yml

- name: Configure motd
  import_tasks: motd.yml
  tags: [common, common_motd]

- name: Install goss
  import_tasks: goss.yml
