---
- name: Install rsyslog
  apt:
    pkg: rsyslog
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

- name: Additional rsyslog config
  copy:
    src: rsyslog/00-custom.conf
    dest: /etc/rsyslog.d/00-custom.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: Copy rsyslog logrotate config
  copy:
    src: rsyslog/logrotate.conf
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
