---
#  SSHD Hardening
#  - https://linux-audit.com/audit-and-harden-your-ssh-configuration/
- name: Install latest SSH  # noqa package-latest 403
  apt:
    pkg: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

- name: Copy secure, global sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0444
  notify: reload ssh
