---
#  TCP Tunning:
#  - http://kaivanov.blogspot.com/2010/09/linux-tcp-tuning.html
#  - https://blog.wwwjfy.net/2013/08/04/basic-server-tuning/
#  - https://fasterdata.es.net/host-tuning/linux/
#  - http://www.streppone.it/cosimo/blog/2011/11/a-collection-of-useful-sysctl-snippets-packaged-as-a-puppet-module/
#  - http://russ.garrett.co.uk/2009/01/01/linux-kernel-tuning/
- name: Default sysctl values
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: run sysctl
