---
- name: Ensure tzdata is installed
  ansible.builtin.apt:
    pkg: tzdata
    state: present
    cache_valid_time: "{{ apt_cache_time }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ time_zone }}"
