---
node_exporter_version: 1.9.1
node_exporter_host: '0.0.0.0'
node_exporter_port: 9100
node_exporter_options: ''

node_exporter_group: "node-exporter"
node_exporter_user: "{{ node_exporter_group }}"
node_exporter_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
# yamllint disable-line rule:line-length
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
node_exporter_bin_path: "/usr/local/bin"
