---
plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.ini', 'url', section='proxmox', file='credentials.ini') }}"
user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
want_facts: true
filters:
  - '"k3s" in proxmox_hostname'
groups:
  k3s: '"k3s" in proxmox_hostname'
  k3s-servers: '"k3s-server" in proxmox_hostname'
  k3s-agents: '"k3s-agent" in proxmox_hostname'
  k3s-data: '"k3s-data" in proxmox_hostname'
compose:
  ansible_host: proxmox_net0.ip | replace("/32", "")
want_proxmox_nodes_ansible_host: false
