---
- name: Configure flare
  block:

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ flare_directory }}"
        state: directory
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ flare_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Copy config files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ flare_directory }}/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - apps.yml
        - bookmarks.yml
        - config.yml

    - name: Create and start app
      community.docker.docker_compose:
        project_src: "{{ flare_directory }}"
        recreate: always
        remove_orphans: true
        remove_volumes: true
        restarted: true

    - name: Wait until site is up
      ansible.builtin.uri:
        url: "https://{{ flare_uri }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 12       # Retries for 12 * 10 secs = 120 secs = 2 mins

  tags: flare
