---
- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    vmid: "{{ proxmox_vmid }}"
    state: stopped
