---
#
# - Docs: https://taskfile.dev/
# - Examples: https://dev.to/stack-labs/introduction-to-taskfile-a-makefile-alternative-h92
#
version: '3'

includes:
  apps-lxc: ./tasks/apps-lxc.yml
  arr-lxc: ./tasks/arr-lxc.yml
  cloudflare: ./tasks/cloudflare.yml
  debug-lxc: ./tasks/debug-lxc.yml
  devbox-lxc: ./tasks/devbox-lxc.yml
  net-lxc: ./tasks/net-lxc.yml
  mon-lxc: ./tasks/mon-lxc.yml
  oracle: ./tasks/oracle.yml
  packer: ./tasks/packer.yml
  proxmox: ./tasks/proxmox.yml
  rpi: ./tasks/rpi.yml

vars:
  ANSIBLE_DIR: ./ansible
  DOMAIN: macminis.net
  KUBERNETES_DIR: ./kubernetes
  PACKER_DIR: ./packer
  TERRAFORM_DIR: ./terraform
  WAIT_SECS_LONG: 120
  WAIT_SECS_MEDIUM: 30
  WAIT_SECS_SHORT: 5
