---
#
# - Docs: https://taskfile.dev/
# - Examples: https://dev.to/stack-labs/introduction-to-taskfile-a-makefile-alternative-h92
#
version: '3'

vars:
  ANSIBLE_DIR: ./ansible
  TERRAFORM_DIR: ./terraform
  KUBERNETES_DIR: ./kubernetes
  PACKER_DIR: ./packer
  WAIT_SECS_LONG: 120
  WAIT_SECS_MEDIUM: 30
  WAIT_SECS_SHORT: 5

includes:
  cloudflare: ./tasks/cloudflare.yml
  homelab: ./tasks/homelab.yml
  k3os: ./tasks/k3os.yml
  k3s: ./tasks/k3s.yml
  nomad: ./tasks/nomad.yml
  oracle: ./tasks/oracle.yml
  packer: ./tasks/packer.yml
  proxmox: ./tasks/proxmox.yml
  talos: ./tasks/talos.yml
