---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include global Ansible variables
      include_vars:
        dir: ../../../../group_vars/all

    - name: Install goss
      include_role:
        name: goss
