---
version: '3'

vars:
  CLOUDFLARE_TF_DIR: "{{.TERRAFORM_DIR}}/cloudflare"

tasks:
  check:
    dir: "{{.CLOUDFLARE_TF_DIR}}"
    desc: Check Cloudflare code
    cmds:
      - terraform fmt && terraform validate
      - terraform plan -compact-warnings

  update:
    dir: "{{.CLOUDFLARE_TF_DIR}}"
    desc: Update Cloudflare DNS entries
    cmds:
      - terraform fmt && terraform validate
      - terraform apply -auto-approve
