---
version: '3'

tasks:
  build:
    dir: "{{.PACKER_DIR}}"
    desc: Build Ubuntu 22.04 template from ISO
    cmds:
      # Always store initial template on "macmini1"
      - ./build --node macmini1 --template ubuntu-22-04-iso
