---
version: '3'

tasks:
  provision:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml

  provision-uptime-kuma:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Uptime-Kuma" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag uptime-kuma

  provision-grafana:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Grafana" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag grafana

  provision-traefik:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Traefik" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag traefik

  provision-prometheus:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Prometheus" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag prometheus

  provision-homer:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Homer" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag homer

  provision-speedtest-tracker:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Homer" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag speedtest_tracker

  provision-dozzle:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Dozzle" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag dozzle
