---
version: '3'

tasks:
  provision:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml

  provision-uptime-kuma:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Uptime-Kuma" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag uptime-kuma

  provision-grafana:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Grafana" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag grafana

  provision-traefik:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Traefik" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag traefik

  provision-prometheus:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Prometheus" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag prometheus

  provision-homer:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Homer" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag homer

  provision-speedtest-tracker:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Homer" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag speedtest_tracker

  provision-dozzle:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Dozzle" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag dozzle

  provision-outline:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Outline" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag outline

  provision-snippet-box:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Snippet-Box" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag snippet_box

  provision-n8n:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "n8n" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag n8n

  provision-rundeck:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Rundeck" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag rundeck

  provision-cronicle:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Cronicle" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag cronicle

  provision-loki:
    dir: "{{.ANSIBLE_DIR}}"
    desc: Provision "Loki" on Portainer LXC
    cmds:
      - ansible-playbook -i inventories/proxmox portainer-provision.yml --tag loki
