---
bookstack_directory: /opt/bookstack
bookstack_volume: data
bookstack_uri: bookstack.{{ global_domain }}
bookstack_port: 80

# idempotent values
bookstack_db_pwd: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=16', seed=inventory_hostname) }}"
