---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include global Ansible variables
      ansible.builtin.include_vars:
        dir: ../../../../group_vars/all

    - name: Install modern_unix
      ansible.builtin.include_role:
        name: modern_unix
