---
# ? Example file:
# ? https://github.com/gswallow/molecule_example/blob/master/molecule/default/molecule.yml
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c ../../../.yamllint .
  ansible-lint -c ../../.ansible-lint
driver:
  name: docker
platforms:
  - name: my_molecule
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    security_opts:
      - seccomp=unconfined
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: true
  config_options:
    defaults:
      stdout_callback: yaml
      callbacks_enabled: yaml,profile_tasks
      bin_ansible_callbacks: true
      force_color: true
verifier:
  name: ansible
