---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Include global Ansible variables
      include_vars:
        dir: ../../../../group_vars/all

    #
    # ! NOTE:
    # ! Include below any tasks you need to execute prior to running any tests
    #
    - name: Update apt caches
      apt:
        update_cache: true
        cache_valid_time: "{{ apt_cache_time }}"

    - name: Install dependencies
      apt:
        pkg: "{{ item }}"
        state: present
      loop:
        - xz-utils
