---
- name: Add no-subscription community repo
  ansible.builtin.copy:
    dest: "{{ repo_sources_folder }}/pve-no-subscription.list"
    content: |
      deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    owner: root
    group: root
    mode: 0644

- name: Disable subscription repo
  ansible.builtin.lineinfile:
    dest: "{{ repo_sources_folder }}/pve-enterprise.list"
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: true
    state: present

- name: Update apt caches
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install default packages
  ansible.builtin.apt:
    pkg: "{{ apt_pkgs_to_install }}"
    state: present
