---
- name: Add no-subscription community repo
  copy:
    dest: "{{ repo_sources_folder }}/pve-no-subscription.list"
    content: |
      deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    owner: root
    group: root
    mode: 0644

- name: Disable subscription repo
  lineinfile:
    dest: "{{ repo_sources_folder }}/pve-enterprise.list"
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Update apt caches
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Install default packages
  apt:
    pkg: "{{ apt_pkgs_to_install }}"
    state: present
