---
repo_sources_folder: /etc/apt/sources.list.d
cloudinit_folder: /var/lib/vz/cloud-init
apt_cache_time: 1800

apt_pkgs_to_install:
  - aptitude
  - curl
  - git
  - grc
  - hddtemp
  - htop
  - lm-sensors
  - locate
  - lsof
  - multitail
  - nano
  - ncdu
  - net-tools
  - nmap
  - tar
  - tree
  - unzip
  - wget
  - zip

aliases: |
  #
  #  Global aliases
  #
  alias ..='cd ../'
  alias ...='cd ../../'
  alias .2='cd ../../'
  alias .3='cd ../../../'
  alias .4='cd ../../../../'
  alias .5='cd ../../../../../'
  alias .6='cd ../../../../../../'
  alias 1='cd +1'
  alias 2='cd +2'
  alias 3='cd +3'
  alias 4='cd +4'
  alias 5='cd +5'
  alias 6='cd +6'
  alias 7='cd +7'
  alias 8='cd +8'
  alias 9='cd +9'
  alias c=clear
  alias cd..='cd ../'
  alias colourify='/usr/bin/grc -es --colour=auto'
  alias configure='colourify ./configure'
  alias cp='cp -iv'
  alias cpi='nocorrect cp -i'
  alias d='dirs -v'
  alias df='colourify df'
  alias diff='colourify diff'
  alias diffu='diff --unified'
  alias dig='colourify dig'
  alias du='colourify du'
  alias egrep='egrep --color=auto'
  alias env='colourify env'
  alias fdisk='colourify fdisk'
  alias fix_stty='stty sane'
  alias free='colourify free'
  alias ftp='noglob ftp'
  alias head='colourify head'
  alias id='colourify id'
  alias ifconfig='colourify ifconfig'
  alias ip='colourify ip'
  alias l='ls -1A'
  alias la='ll -A'
  alias lc='lt -c'
  alias ld='colourify ld'
  alias less='less -FSRXc'
  alias lk='ll -Sr'
  alias ll='ls -FGlAhp'
  alias lm='la | "$PAGER"'
  alias locate='noglob locate'
  alias lr='ll -R'
  alias lsblk='colourify lsblk'
  alias lsof='colourify lsof'
  alias lspci='colourify lspci'
  alias lt='ll -tr'
  alias lu='lt -u'
  alias lx='ll -XB'
  alias mkdir='mkdir -pv'
  alias mount='colourify mount'
  alias mv='mv -iv'
  alias my_ip='dig +short myip.opendns.com @resolver1.opendns.com'
  alias netstat='colourify netstat'
  alias path='echo -e ${PATH//:/\\n}'
  alias ping='colourify ping'
  alias ps='colourify ps'
  alias psc='ps xao pid,state,user,args'
  alias pu=pushd
  alias rrsync='rsync --rsync-path sudo\ rsync --recursive --perms --copy-links --verbose --compress --rsh=ssh'
  alias rsync='noglob rsync'
  alias run-help=man
  alias sa='alias | grep -i'
  alias scp='noglob scp'
  alias sftp='noglob sftp'
  alias show_options=shopt
  alias sl=ls
  alias sudo='sudo '
  alias sum='xargs | tr '' '' ''+'' | bc'
  alias tail='colourify tail'
  alias topc='top -o cpu'
  alias topm='top -o vsize'
  alias traceroute='colourify traceroute'
  alias traceroute6='colourify traceroute6'
  alias type='type -a'
  alias vi='vim -p'
  alias xx='exa --long -a --header --grid'
  alias '~'='cd ~'

prompt: |
  #
  #  Global Bash Prompt
  #
  export PS1='\[\033[1;32m\]\u\[\033[0m\]@\[\033[1;30m\]\H\[\033[0m\]:\[\033[0;34m\]\w\[\033[0m\]\$ '

dns: |
  search local
  nameserver 1.1.1.1
  nameserver 1.0.0.1

#
#  ISO images
#
os_image_folder: /mnt/pve/remote-nfs/template/iso
os_image_list:
  -
    # ! No longer available for download, keep "as-is"
    codename: ubuntu_focal_minimal
    version: 20.04
    iso: ubuntu_20_04_minimal.iso
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso
    checksum: sha256:0e79e00bf844929d40825b1f0e8634415cda195ba23bae0b041911fde4dfe018
  -
    codename: ubuntu_jammy
    version: 22.04
    iso: ubuntu-22.04.5-live-server-amd64.iso
    url: https://releases.ubuntu.com/jammy/ubuntu-22.04.5-live-server-amd64.iso
    checksum: sha256:9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0
  -
    codename: ubuntu_noble_numbat
    version: 24.04
    iso: ubuntu-24.04.2-live-server-amd64.iso
    url: https://mirror.us.leaseweb.net/ubuntu-releases/24.04.2/ubuntu-24.04.2-live-server-amd64.iso
    checksum: sha256:d6dab0c3a657988501b4bd76f1297c053df710e06e0c3aece60dead24f270b4d
  -
    codename: talos
    version: 1.9.5
    iso: talos-amd64.iso
    url: https://github.com/siderolabs/talos/releases/download/v1.9.5/metal-amd64.iso
    checksum: sha256:b85af09aeef9b510648f14280fdb4e1ecd676e462e39f1c0f56388a0cf34fc5a
  -
    codename: nixos-gnome
    version: 24.11
    iso: nixos-gnome-x86_64-linux.iso
    url: https://channels.nixos.org/nixos-24.11/latest-nixos-gnome-x86_64-linux.iso
    checksum: sha256:f2935c3d24372eec5d94dfc9577693cce754b391d0265194cd71864261139dc5.
  -
    codename: nixos-minimal
    version: 24.11
    iso: nixos-minimal-x86_64-linux.iso
    url: https://channels.nixos.org/nixos-24.11/latest-nixos-minimal-x86_64-linux.iso
    checksum: sha256:659a056261404810703188b986b818a723fd0bcf650e58c1ea9857086612822a
