plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.ini', 'url', section='proxmox', file='credentials.ini') }}"
user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
want_facts: true
filters:
  - '"nomad" in proxmox_name'
groups:
  nomad: '"nomad" in proxmox_name'
  nomad-servers: '"nomad-server" in proxmox_name'
  nomad-agents: '"nomad-agent" in proxmox_name'
compose:
  ansible_host: proxmox_net0.ip | replace("/32", "")
want_proxmox_nodes_ansible_host: false
