---
hostname: k3os-server-01
ssh_authorized_keys:
  - github:ifarfan
write_files:
  - path: /var/lib/connman/default.config
    content: |-
      [service_eth0]
      Type=ethernet
      IPv4=192.168.136.41/255.255.255.0/192.168.136.1
      IPv6=off
      Nameservers=1.1.1.1,1.0.0.1
  - path: /var/lib/rancher/k3s/server/manifests/kube-vip.yml
    encoding: ""
    content: |-
      ---
      #
      # See: https://kube-vip.io/manifests/rbac.yaml
      #
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kube-vip
        namespace: kube-system
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: "true"
        name: system:kube-vip-role
      rules:
        - apiGroups: [""]
          resources: ["services", "services/status", "nodes", "endpoints"]
          verbs: ["list", "get", "watch", "update"]
        - apiGroups: ["coordination.k8s.io"]
          resources: ["leases"]
          verbs: ["list", "get", "watch", "update", "create"]
      ---
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: system:kube-vip-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kube-vip-role
      subjects:
        - kind: ServiceAccount
          name: kube-vip
          namespace: kube-system
      ---
      #
      # See: https://kube-vip.io/docs/installation/daemonset/#example-arp-manifest
      #
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-vip-ds
        namespace: kube-system
      spec:
        selector:
          matchLabels:
            name: kube-vip-ds
        template:
          metadata:
            labels:
              name: kube-vip-ds
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: Exists
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
            containers:
              - args:
                  - manager
                env:
                  - name : lb_enable
                    value: "true"
                  - name: vip_arp
                    value: "true"
                  - name: port
                    value: "6443"
                  - name: vip_interface
                    value: eth0
                  - name: vip_cidr
                    value: "32"
                  - name: cp_enable
                    value: "true"
                  - name: cp_namespace
                    value: kube-system
                  - name: vip_ddns
                    value: "false"
                  - name: svc_enable
                    value: "true"
                  - name: vip_leaderelection
                    value: "true"
                  - name: vip_leaseduration
                    value: "15"
                  - name: vip_renewdeadline
                    value: "10"
                  - name: vip_retryperiod
                    value: "2"
                  - name: address
                    value: 192.168.136.40     # kube-vip IP address
                image: ghcr.io/kube-vip/kube-vip:v0.5.0
                imagePullPolicy: Always
                name: kube-vip
                resources: {}
                securityContext:
                  capabilities:
                    add:
                      - NET_ADMIN
                      - NET_RAW
                      - SYS_TIME
            hostNetwork: true
            serviceAccountName: kube-vip
            tolerations:
              - effect: NoSchedule
                operator: Exists
              - effect: NoExecute
                operator: Exists
        updateStrategy: {}
      status:
        currentNumberScheduled: 0
        desiredNumberScheduled: 0
        numberMisscheduled: 0
        numberReady: 0
    owner: root
    permissions: '0644'
k3os:
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
  dns_nameservers:
    - 1.1.1.1
    - 1.0.0.1
  k3s_args:
    - server
    - "--cluster-init"
    - "--disable=servicelb"
    - "--disable=traefik"
    - "--bind-address=192.168.136.41"
    - "--tls-san=192.168.136.40"                                        # kube-vip IP address
    - "--node-taint=node-role.kubernetes.io/master=true:NoSchedule"     # needed by kube-vip
    - "--token=e6saw26p88bhukn7uuyr9ay8t45xyz4pw6664km5erzw5utr5vjhdrutbwz9s7zkejnz6yhuts8bm2p3u6zzht4ydphw3pyenqc"
