---
- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: reload iptables
  ansible.builtin.shell:
    iptables-restore < /etc/iptables/rules.v4
