---
#
# ? Ubuntu post-provisioning testing
#
- name: Test Ubuntu 20.04
  hosts: default
  become: true
  gather_facts: true

  tasks:
    - name: Run Ubuntu tests
      include_role:
        name: run_tests
      vars:
        role_to_test: base
