---
- name: Configure dashy
  block:

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ dashy_directory }}"
        state: directory
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ dashy_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Copy config.yml file
      ansible.builtin.template:
        src: conf.yml.j2
        dest: "{{ dashy_directory }}/conf.yml"
        owner: root
        group: root
        mode: 0644

    - name: Create and start app
      community.docker.docker_compose:
        project_src: "{{ dashy_directory }}"

    - name: Wait until site is up
      ansible.builtin.uri:
        url: "https://dashy.{{ global_domain }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 12       # Retries for 12 * 10 secs = 120 secs = 2 mins

  tags: dashy
