---
outline_directory: /opt/outline
outline_volume: outline_data
outline_uri: outline.{{ global_domain }}
outline_port: 3000

# Secrets
outline_secret_key: "{{ lookup('ansible.builtin.ini', 'secret_key', section='outline', file='credentials.ini') }}"
outline_utils_secret: "{{ lookup('ansible.builtin.ini', 'utils_secret', section='outline', file='credentials.ini') }}"
slack_client_id: "{{ lookup('ansible.builtin.ini', 'client_id', section='slack', file='credentials.ini') }}"
slack_client_secret: "{{ lookup('ansible.builtin.ini', 'client_secret', section='slack', file='credentials.ini') }}"
google_client_id: "{{ lookup('ansible.builtin.ini', 'client_id', section='google', file='credentials.ini') }}"
google_client_secret: "{{ lookup('ansible.builtin.ini', 'client_secret', section='google', file='credentials.ini') }}"
