---
- name: Homelab provisioning
  hosts: homelab
  become: true
  gather_facts: true
  tasks:
    # Base OS install + fixings
    - name: Install Ubuntu 22.04 lxc
      ansible.builtin.include_role:
        name: base
      vars:
        is_lxc: true

    - name: Install modern Unix utilities
      ansible.builtin.include_role:
        name: modern_unix

    # Docker daemon + docker compose apps
    - name: Install docker
      ansible.builtin.include_role:
        name: docker

    - name: Install traefik
      ansible.builtin.include_role:
        name: traefik
      tags: traefik

    - name: Install portainer
      ansible.builtin.include_role:
        name: portainer
      tags: portainer

    - name: Install uptime-kuma
      ansible.builtin.include_role:
        name: uptime_kuma
      tags: uptime_kuma

    - name: Install prometheus
      ansible.builtin.include_role:
        name: prometheus
      tags: prometheus

    - name: Install grafana
      ansible.builtin.include_role:
        name: grafana
      tags: grafana

    - name: Install speedtest-tracker
      ansible.builtin.include_role:
        name: speedtest_tracker
      tags: speedtest_tracker

    - name: Install dozzle
      ansible.builtin.include_role:
        name: dozzle
      tags: dozzle

    - name: Install outline
      ansible.builtin.include_role:
        name: outline
      tags: outline

    - name: Install snippet-box
      ansible.builtin.include_role:
        name: snippet_box
      tags: snippet_box

    # - name: Install n8n
    #   ansible.builtin.include_role:
    #     name: n8n
    #   tags: n8n

    - name: Install loki
      ansible.builtin.include_role:
        name: loki
      tags: loki

    - name: Install homepage
      ansible.builtin.include_role:
        name: homepage
      tags: homepage

    - name: Install 'what's up docker'
      ansible.builtin.include_role:
        name: wud
      tags: wud

    - name: Install linkding
      ansible.builtin.include_role:
        name: linkding
      tags: linkding

    - name: Install rustdesk
      ansible.builtin.include_role:
        name: rustdesk
      tags: rustdesk

    - name: Install navidrome
      ansible.builtin.include_role:
        name: navidrome
      tags: navidrome

    - name: Install guacamole
      ansible.builtin.include_role:
        name: guacamole
      tags: guacamole

    - name: Install swingmusic
      ansible.builtin.include_role:
        name: swingmusic
      tags: swingmusic
