---
#
# ? Stop all nodes in this order
# ? - agents
# ? - data
# ? - servers
#
- name: Stop k3os agent hosts
  hosts: k3os_agents
  gather_facts: false
  tasks:
    - name: Stop agent nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        name: "{{ inventory_hostname }}"
        state: stopped
      delegate_to: localhost

- name: Stop k3os data hosts
  hosts: k3os_data
  gather_facts: false
  tasks:
    - name: Stop data nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        name: "{{ inventory_hostname }}"
        state: stopped
      delegate_to: localhost

- name: Stop k3os server hosts
  hosts: k3os_servers
  gather_facts: false
  tasks:
    - name: Stop server nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        name: "{{ inventory_hostname }}"
        state: stopped
      delegate_to: localhost
