---
#
# ? Playbook vars + copy k3os script
#
- name: Playbook vars + copy k3os script
  hosts: m1.macminis.net
  become: true
  gather_facts: false
  tasks:
    - name: Define global vars
      ansible.builtin.set_fact:
        cmd_cluster_init: []
        cmd_servers: []
        cmd_agents: []
        list_custer_init: []
        list_servers: []
        list_agents: []
    - name: Copy k3os init script
      ansible.builtin.copy:
        src: files/k3os-vm-init
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755

#
# ? Generate cluster + servers + agents script commands
#
- name: Generate cluster init command
  hosts: k3os-server-01.macminis.net
  gather_facts: false
  serial: 1
  tasks:
    - name: Define cluster init command
      ansible.builtin.set_fact:
        cmd_string: "k3os-vm-init --proxmox_node {{ proxmox_node }} --vm_id {{ proxmox_vmid }} --vm_name {{ inventory_hostname_short }}"

    - name: Append cluster init command to list
      ansible.builtin.set_fact:
        cmd_cluster_init: "{{ hostvars['m1.macminis.net'].cmd_cluster_init + [ cmd_string ] }}"
        list_custer_init: "{{ hostvars['m1.macminis.net'].list_custer_init + [ inventory_hostname ] }}"
      delegate_to: m1.macminis.net
      delegate_facts: true

- name: Generate servers init commands
  hosts: k3os_servers:!k3os-server-01.macminis.net
  gather_facts: false
  serial: 1
  tasks:
    - name: Define server command
      ansible.builtin.set_fact:
        cmd_string: "k3os-vm-init --proxmox_node {{ proxmox_node }} --vm_id {{ proxmox_vmid }} --vm_name {{ inventory_hostname_short }}"

    - name: Append server command to list
      ansible.builtin.set_fact:
        cmd_servers: "{{ hostvars['m1.macminis.net'].cmd_servers + [ cmd_string ] }}"
        list_servers: "{{ hostvars['m1.macminis.net'].list_servers + [ inventory_hostname ] }}"
      delegate_to: m1.macminis.net
      delegate_facts: true

- name: Generate agents init commands
  hosts: k3os_agents, k3os_data
  gather_facts: false
  serial: 1
  tasks:
    - name: Define agent command
      ansible.builtin.set_fact:
        cmd_string: "k3os-vm-init --proxmox_node {{ proxmox_node }} --vm_id {{ proxmox_vmid }} --vm_name {{ inventory_hostname_short }}"

    - name: Append agent command to list
      ansible.builtin.set_fact:
        cmd_agents: "{{ hostvars['m1.macminis.net'].cmd_agents + [ cmd_string ] }}"
        list_agents: "{{ hostvars['m1.macminis.net'].list_agents + [ inventory_hostname ] }}"
      delegate_to: m1.macminis.net
      delegate_facts: true

#
# ? Initialize cluster
#
- name: Initialize cluster
  hosts: m1.macminis.net
  become: true
  gather_facts: false
  tasks:
    - name: Show cluster init commands
      ansible.builtin.debug:
        var: "{{ item }}"
      with_items: cmd_cluster_init

    - name: Initialize cluster
      ansible.builtin.command: "{{ item }}"
      register: cluster_init_output
      with_items: "{{ cmd_cluster_init }}"

    - name: Wait until cluster-init server is accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ item }}"
        delay: 5
      with_items: "{{ list_custer_init }}"

#
# ? Initialize + join remaining servers + agents to cluster
#
- name: Initialize nodes
  hosts: m1.macminis.net
  become: true
  gather_facts: false
  tasks:
    # Servers joining cluster
    - name: Show servers join cluster commands
      ansible.builtin.debug:
        var: "{{ item }}"
      with_items: cmd_servers

    - name: Initialize + join servers to cluster
      ansible.builtin.command: "{{ item }}"
      register: cmd_servers_output
      with_items: "{{ cmd_servers }}"

    - name: Wait until servers are accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ item }}"
        delay: 5
      with_items: "{{ list_servers }}"

    # Agents joining cluster
    - name: Show agents join cluster commands
      ansible.builtin.debug:
        var: "{{ item }}"
      with_items: cmd_agents

    - name: Initialize + join agents to cluster
      ansible.builtin.command: "{{ item }}"
      register: cmd_agents_output
      with_items: "{{ cmd_agents }}"

    - name: Wait until agents are accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 22
        host: "{{ item }}"
        delay: 5
      with_items: "{{ list_agents }}"
