---
#
# ? Start all nodes in this order
# ? - servers
# ? - data
# ? - agents
#
- name: Start k3os server hosts
  hosts: k3os_servers
  gather_facts: false
  tasks:
    - name: Start server nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost

- name: Start k3os data hosts
  hosts: k3os_data
  gather_facts: false
  tasks:
    - name: Start data nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost

- name: Start k3os agent hosts
  hosts: k3os_agents
  gather_facts: false
  tasks:
    - name: Start agent nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost
