---
# ? Start all nodes in this order
# ? - servers
# ? - data
# ? - agents
- name: Set Proxmox variables
  hosts: localhost
  tasks:
    - name: Set Proxmox variables
      ansible.builtin.set_fact:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"

- name: Start k3os server hosts
  hosts: k3os_servers
  gather_facts: false
  tasks:
    - name: Start server nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        name: "{{ inventory_hostname }}"
        state: started
      delegate_to: localhost

    - name: Wait until server nodes are accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ inventory_hostname }}"
        delay: 5

- name: Start k3os data hosts
  hosts: k3os_data
  gather_facts: false
  tasks:
    - name: Start data nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        name: "{{ inventory_hostname }}"
        state: started
      delegate_to: localhost

    - name: Wait until data nodes are accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 5

- name: Start k3os agent hosts
  hosts: k3os_agents
  gather_facts: false
  tasks:
    - name: Start agent nodes
      throttle: 1
      community.general.proxmox_kvm:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        name: "{{ inventory_hostname }}"
        state: started
      delegate_to: localhost

    - name: Wait until agent nodes are accesible (timeout 5 mins)
      ansible.builtin.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 5
