---
#
# ? Reboot all nodes in this order
# ? - servers
# ? - agents
# ? - data
#
- name: Reboot k3os server hosts
  hosts: k3os_servers
  gather_facts: false
  connection: local
  tasks:
    - name: Reboot server nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: restarted

- name: Reboot k3os agent hosts
  hosts: k3os_agents
  gather_facts: false
  connection: local
  tasks:
    - name: Reboot agent nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: restarted

- name: Reboot k3os data hosts
  hosts: k3os_data
  gather_facts: false
  connection: local
  tasks:
    - name: Reboot data nodes
      throttle: 1
      community.general.proxmox:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: restarted
