---
# ? Start all nodes in this order
# ? - servers
# ? - data
# ? - agents
- name: Set Proxmox variables
  hosts: localhost
  tasks:
    - name: Set Proxmox variables
      ansible.builtin.set_fact:
        api_host: "{{ lookup('ansible.builtin.ini', 'host', section='proxmox', file='credentials.ini') }}"
        api_user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
        api_password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"

- name: Start k3s server hosts
  hosts: k3s_servers
  gather_facts: false
  tasks:
    - name: Start server nodes   # noqa 504
      throttle: 1
      community.general.proxmox:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost

- name: Start k3s data hosts
  hosts: k3s_data
  gather_facts: false
  tasks:
    - name: Start data nodes   # noqa 504
      throttle: 1
      community.general.proxmox:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost

- name: Start k3s agent hosts
  hosts: k3s_agents
  gather_facts: false
  tasks:
    - name: Start agent nodes   # noqa 504
      throttle: 1
      community.general.proxmox:
        api_host: "{{ hostvars['localhost'].api_host }}"
        api_user: "{{ hostvars['localhost'].api_user }}"
        api_password: "{{ hostvars['localhost'].api_password }}"
        hostname: "{{ inventory_hostname }}"
        unprivileged: true
        state: started
      delegate_to: localhost
