---
- name: LXC host provisioning
  hosts: proxmox_all_lxc
  become: true
  gather_facts: true
  tasks:
    - name: Install Ubuntu 22.04 lxc
      ansible.builtin.include_role:
        name: base
      vars:
        is_lxc: true

    - name: Install modern Unix utilities
      ansible.builtin.include_role:
        name: modern_unix
