---
- name: Update Proxmox servers
  hosts: macminis
  become: true
  gather_facts: false
  tasks:
    - name: Update Proxmox nodes
      ansible.builtin.include_role:
        name: proxmox

    - name: Reboot 1 proxmox node at the time + wait up to 3 mins
      throttle: 1
      ansible.builtin.reboot:
        post_reboot_delay: 60
        reboot_timeout: 180
        # test_command: /usr/bin/systemctl status pvedaemon
