---
- name: Portainer provisioning
  hosts: portainer
  become: true
  gather_facts: true
  tasks:
    # Base OS install + fixings
    - name: Install Ubuntu 22.04 lxc
      ansible.builtin.include_role:
        name: base/lxc

    - name: Install modern Unix utilities
      ansible.builtin.include_role:
        name: modern_unix

    # Docker daemon + docker compose apps
    - name: Install docker
      ansible.builtin.include_role:
        name: docker

    - name: Install traefik
      ansible.builtin.include_role:
        name: traefik
      tags: traefik

    - name: Install portainer
      ansible.builtin.include_role:
        name: portainer
      tags: portainer

    - name: Install uptime-kuma
      ansible.builtin.include_role:
        name: uptime_kuma
      tags: uptime_kuma

    - name: Install prometheus
      ansible.builtin.include_role:
        name: prometheus
      tags: prometheus

    - name: Install grafana
      ansible.builtin.include_role:
        name: grafana
      tags: grafana

    - name: Install homer
      ansible.builtin.include_role:
        name: homer
      tags: homer

    - name: Install speedtest-tracker
      ansible.builtin.include_role:
        name: speedtest_tracker
      tags: speedtest_tracker

    - name: Install dozzle
      ansible.builtin.include_role:
        name: dozzle
      tags: dozzle

    - name: Install outline
      ansible.builtin.include_role:
        name: outline
      tags: outline

    - name: Install snippet-box
      ansible.builtin.include_role:
        name: snippet_box
      tags: snippet_box

    - name: Install n8n
      ansible.builtin.include_role:
        name: n8n
      tags: n8n

    - name: Install rundeck
      ansible.builtin.include_role:
        name: rundeck
      tags: rundeck

    - name: Install cronicle
      ansible.builtin.include_role:
        name: cronicle
      tags: cronicle

    - name: Install loki
      ansible.builtin.include_role:
        name: loki
      tags: loki
