---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include global Ansible variables
      ansible.builtin.include_vars:
        dir: ../../../../group_vars/all

    - name: Install Ubuntu 22.04
      ansible.builtin.include_role:
        name: ubuntu_22_04
