plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.ini', 'url', section='proxmox', file='credentials.ini') }}"
user: "{{ lookup('ansible.builtin.ini', 'user', section='proxmox', file='credentials.ini') }}"
password: "{{ lookup('ansible.builtin.ini', 'password', section='proxmox', file='credentials.ini') }}"
want_facts: true
filters:
  - '"talos" in proxmox_name'
groups:
  talos: '"talos" in proxmox_name'
  talos-servers: '"talos-server" in proxmox_name'
  talos-agents: '"talos-agent" in proxmox_name'
  talos-data: '"talos-data" in proxmox_name'
compose:
  ansible_host: proxmox_net0.ip | replace("/32", "")
want_proxmox_nodes_ansible_host: false
