---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Include global Ansible variables
      ansible.builtin.include_vars:
        dir: ../../../../group_vars/all

    # ! NOTE:
    # ! Include below any tasks you need to execute
    # ! prior to running any role tests
    - name: Create "ubuntu" group
      ansible.builtin.group:
        name: ubuntu
        state: present

    - name: Create "ubuntu" user
      ansible.builtin.user:
        name: ubuntu
        group: ubuntu
        comment: The man, the legend
        state: present
        shell: /bin/bash
        create_home: true

    - name: Install Goss
      ansible.builtin.include_role:
        name: goss
