---
- name: Verify
  hosts: all
  become: true
  vars:
    goss_folder: /tmp/molecule/goss
  tasks:
    - name: Create goss folder for test files
      file:
        path: "{{ goss_folder }}"
        state: directory
        mode: 0755

    - name: Find goss files
      set_fact:
        goss_files: "{{ lookup('fileglob', '../tests/*.yml', wantlist=True) | sort }}"

    - name: Copy goss tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ goss_folder }}/{{ item | basename }}"
        mode: 0755
      with_items:
        - "{{ goss_files }}"

    - name: List goss files
      debug:
        msg: "{{ item | basename }}"
      loop: "{{ goss_files }}"

    - name: Run goss tests
      command:
        goss --gossfile {{ goss_folder }}/{{ item | basename }} validate --format documentation
      register: test_results
      with_items: "{{ goss_files }}"
      failed_when: false
      changed_when: false

    - name: Display goss tests results
      debug:
        msg: "[command]:\n{{ item.cmd | join(' ') }}\n\n[output]:\n{{ item.stdout }}\n\n[return code]:\n{{ item.rc }}"
      loop: "{{ test_results.results }}"
      loop_control:
        label: "{{ item.changed }}"
      failed_when: item.rc != 0
