---
- name: Configure docker logging
  ansible.builtin.copy:
    dest: /etc/docker/daemon.js
    content: |
      {
        "debug": true,
        "log-driver": "loki",
        "log-opts": {
          "loki-url": "http://localhost:{{ loki_port }}/loki/api/v1/push",
          "loki-batch-size": "400"
        }
      }
    owner: root
    group: root
    mode: 0644
  notify: restart docker
