---
- name: Configure speedtest-tracker
  block:

    - name: Create speedtest-tracker directory
      ansible.builtin.file:
        path: "{{ speedtest_tracker_directory }}"
        state: directory
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ speedtest_tracker_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644
        backup: true

    - name: Create and start speedtest-tracker
      community.docker.docker_compose:
        project_src: "{{ speedtest_tracker_directory }}"
        recreate: always
        remove_orphans: true
        remove_volumes: true
        restarted: true

    - name: Wait until site is up
      ansible.builtin.uri:
        url: "https://{{ speedtest_tracker_uri }}/"
        validate_certs: true
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 12       # Retries for 12 * 10 secs = 120 secs = 2 mins
      delay: 10
      register: uri_output

  tags: speedtest_tracker
